from django.conf.urls import url, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from .views import (
    UserListCreateView,
    UserLoginView,
    UserLogoutView,
    PasswordChangeView,
    OtpTokenView,
    OtpValidationView,
    PasswordResetView,
    UserRetrieveUpdateDeleteView,
    ProfileListCreateView,
    ProfileRetrieveUpdateDeleteView,
    PremiumListCreateView,
    PremiumRetrieveUpdateDeleteView,
    PremiumBookingListCreateView,
    PremiumBookingRetrieveUpdateDeleteView,
    EventListCreateView,
    EventRetrieveUpdateDeleteView,
    StudioListCreateView,
    StudioRetrieveUpdateDeleteView,
)

urlpatterns = [
    url(r'^obtaintoken/', obtain_jwt_token, name='token'),
    url(r'^refreshtoken/', refresh_jwt_token, name='token'),
    url(r'^verifytoken/', verify_jwt_token, name='token'),
    url(r'^user/$', UserListCreateView.as_view(), name='user'),
    url(r'^user/(?P<pk>\d+)/$', UserRetrieveUpdateDeleteView.as_view(), name='user'),
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),
    url(r'^pchange/(?P<pk>\d+)/$',
        PasswordChangeView.as_view(), name='password-change'),
    url(r'^profile/$', ProfileListCreateView.as_view(), name='profile'),
    url(r'^profile/(?P<pk>\d+)/$',
        ProfileRetrieveUpdateDeleteView.as_view(), name='profile'),
    url(r'^event/$', EventListCreateView.as_view(), name='event'),
    url(r'^event/(?P<pk>\d+)/$',
        EventRetrieveUpdateDeleteView.as_view(), name='event'),
    url(r'^studio/$', StudioListCreateView.as_view(), name='studio'),
    url(r'^studio/(?P<pk>\d+)/$',
        StudioRetrieveUpdateDeleteView.as_view(), name='studio'),
    url(r'^getotp/$', OtpTokenView.as_view(), name='otp-token'),
    url(r'^otpvalidate/$', OtpValidationView.as_view(), name='opt-validation'),
    url(r'^preset/(?P<pk>\d+)/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'^password/', include('django_rest_passwordreset.urls',
                               namespace='password_reset')),
    url(r'^premium/$', PremiumListCreateView.as_view(), name='premium'),
    url(r'^premium/(?P<pk>\d+)/$',
        PremiumRetrieveUpdateDeleteView.as_view(), name='studio'),
    url(r'^premiumbook/$', PremiumBookingListCreateView.as_view(), name='profile'),
    url(r'^premiumbook/(?P<pk>\d+)/$',
        PremiumBookingRetrieveUpdateDeleteView.as_view(), name='studio'),
]
