# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
