# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='studio-img'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='studio-img'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='studio-img'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='studio-img'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='studio-img'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='specility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='studio-video'),
        ),
    ]
