# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumbooking',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiumbook', to='accounts.Premium'),
        ),
    ]
