# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190722_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latidute',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longidute',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
