# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190722_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date_of_event', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('casting', models.CharField(max_length=500)),
                ('cast_per_member', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats', models.IntegerField()),
                ('latidute', models.FloatField()),
                ('longitude', models.FloatField()),
                ('specility', models.CharField(max_length=255)),
                ('property_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio-img')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='StudioVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='studio-video')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Studio')),
            ],
        ),
    ]
