# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_premiumbooking_user_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumbooking',
            name='is_premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
