# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studio_cost_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioimage',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.Studio'),
        ),
    ]
