# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_premiumbooking_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumbooking',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='premiumbooking',
            name='premium_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Premium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premiumbooking',
            name='premium',
            field=models.BooleanField(),
        ),
    ]
