# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190731_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='no_of_months',
            new_name='no_of_days',
        ),
        migrations.AddField(
            model_name='premiumbooking',
            name='no_of_days',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
